name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # Call the lint workflow first
  lint:
    uses: ./.github/workflows/lint.yml

  # Call the test workflow first
  test:
    uses: ./.github/workflows/test.yml

  # Call the build workflow first
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true
        cache: true

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: 2
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
